"""
Basis Agent: compound name normalisation for DWSIM.

Converts user-supplied chemical names (trivial names, abbreviations, trade names,
mixture aliases) into exact DWSIM compound names before the Planner runs.

Two-stage design
────────────────
Stage 1 — Deterministic lookup (zero LLM cost):
    Parses compound_database.md at import time into four structures:
      _LOOKUP       : {alias_lower → dwsim_name}
      _MIXTURES     : {alias_lower → [dwsim_names]}
      _MIXTURE_FRACS: {alias_lower → {dwsim_name → mole_fraction}}
      _UNSUPPORTED  : {keyword_lower → reason}   (formal + colloquial names)
    Scans description for known aliases using word-boundary regex (no substrings).
    Results become *anchors* — candidate compounds passed to Stage 2 for verification.

Stage 2 — LLM verifier-completer (always runs):
    Receives the process description plus Stage 1 anchors.
    Three tasks:
      (a) Verify anchors — reject false positives (e.g. "He" matched Helium in prose).
      (b) Complete — find compounds Stage 1 missed (IUPAC names, novel trade names).
      (c) Extract concentration hints and mixture compositions from context.
    Output: confirmed DWSIM names + warnings/errors for unsupported / unverified.

Stage 2 fallback:
    If the LLM call fails (network error, rate limit, quota exhausted), the agent
    falls back to Stage 1 anchors with a WARNING — never silently drops compounds.

Knowledge base:
    context/compound_database.md — single source of truth.
    Add compounds there; no Python changes required.
    Parsed on every BasisAgent instantiation so .md edits take effect immediately.

BasisResult fields:
    compound_map          : {original_text → dwsim_name or [dwsim_names]}
    dwsim_compounds       : flat de-duplicated list of DWSIM names
    normalised_description: description with mentions replaced by DWSIM names
    suggested_compositions: {mixture_alias → {dwsim_name → mole_fraction}}
    concentration_hints   : textual hints about concentrations / compositions
    warnings              : non-fatal issues (unverified names, mixture expansions)
    errors                : fatal issues (unsupported compounds found)
    success               : False when errors is non-empty
    stage                 : "LOOKUP" | "LLM" | "PARTIAL"  (PARTIAL = LLM fallback)
    stage1_count          : number of anchors supplied by Stage 1
"""
from __future__ import annotations
import difflib
import json
import re
from dataclasses import dataclass, field
from pathlib import Path
from string import Template

_CAS_RE = re.compile(r'^\d{1,7}-\d{2}-\d$')

from agents.llm import chat, DEFAULT_MODEL, retry_temperature
from agents.compound_normalize import canonicalize_list
from context import COMPOUND_DATABASE

# ── Full DWSIM compound list (for fuzzy validation of LLM-proposed names) ─────
# Generated by rag/dump_compounds.py — absent before first run, gracefully skipped.
_DWSIM_ALL: dict[str, str] = {}   # lowercase → canonical DWSIM name
_dwsim_list_path = Path(__file__).resolve().parent.parent / "rag" / "sources" / "dwsim_compounds.txt"
if _dwsim_list_path.exists():
    with open(_dwsim_list_path) as _f:
        for _line in _f:
            _name = _line.strip()
            if _name and not _name.startswith("#"):
                _DWSIM_ALL[_name.lower()] = _name

# ── Compound synonym map (alias → canonical DWSIM name) ───────────────────────
# rag/sources/compound_synonyms.json maps each DWSIM name to a list of synonyms.
# Inverted here so any synonym can be looked up in O(1).
_DWSIM_SYNONYMS: dict[str, str] = {}   # synonym_lower → canonical DWSIM name
_synonyms_path = Path(__file__).resolve().parent.parent / "rag" / "sources" / "compound_synonyms.json"
if _synonyms_path.exists():
    with open(_synonyms_path) as _sf:
        _syn_data: dict[str, list[str]] = json.load(_sf)
    for _canonical, _syn_list in _syn_data.items():
        for _syn in _syn_list:
            _DWSIM_SYNONYMS[_syn.lower()] = _canonical


def _levenshtein(a: str, b: str) -> int:
    """Edit distance between two strings (pure Python, O(len(a)*len(b)))."""
    if len(a) < len(b):
        a, b = b, a
    prev = list(range(len(b) + 1))
    for i, ca in enumerate(a):
        curr = [i + 1]
        for j, cb in enumerate(b):
            curr.append(min(prev[j + 1] + 1, curr[j] + 1,
                            prev[j] + (ca != cb)))
        prev = curr
    return prev[-1]


# ── Database parsing ───────────────────────────────────────────────────────────

def _parse_database(
        md: str,
) -> tuple[dict, dict, dict, dict, set]:
    """
    Parse compound_database.md into five structures.

    Returns
    -------
    lookup        : {alias_lower → dwsim_name}
    mixtures      : {alias_lower → [dwsim_names]}
    mixture_fracs : {alias_lower → {dwsim_name → mole_fraction}}
    unsupported   : {keyword_lower → reason}   (formal AND colloquial names)
    unverified    : {dwsim_name}               (? status — warn at runtime)
    """
    lookup:        dict[str, str]             = {}
    mixtures:      dict[str, list[str]]       = {}
    mixture_fracs: dict[str, dict[str, float]] = {}
    unsupported:   dict[str, str]             = {}
    unverified:    set[str]                   = set()

    section = None
    for line in md.splitlines():
        line = line.strip()

        if "Single-Component Aliases" in line:
            section = "single";     continue
        if "Multi-Component Mixture" in line:
            section = "mixture";    continue
        if "Unsupported Compounds" in line:
            section = "unsupported"; continue
        if line.startswith("## ") or line.startswith("# "):
            section = None;         continue

        if not line.startswith("|") or line.startswith("| ---") or line.startswith("|---"):
            continue
        cols = [c.strip() for c in line.split("|") if c.strip()]
        if not cols:
            continue

        # ── Single-component ──────────────────────────────────────────────────
        if section == "single" and len(cols) >= 3:
            dwsim_name  = cols[0]
            cas_raw     = cols[1].strip()
            aliases_raw = cols[2]               # col 1 = CAS
            verified    = cols[4].strip() if len(cols) >= 5 else "?"
            # Split on ", " (comma+space) to preserve names like N,N-dimethylformamide
            aliases = [a.strip() for a in aliases_raw.split(", ") if len(a.strip()) >= 3]
            lookup[dwsim_name.lower()] = dwsim_name
            # CAS number as a direct lookup key (e.g. "7732-18-5" → "Water")
            if _CAS_RE.match(cas_raw):
                lookup[cas_raw] = dwsim_name
            for alias in aliases:
                lookup[alias.lower()] = dwsim_name
            if "?" in verified:
                unverified.add(dwsim_name)

        # ── Multi-component mixture ───────────────────────────────────────────
        elif section == "mixture" and len(cols) >= 2:
            alias_raw    = cols[0]
            alias_lower  = alias_raw.lower()
            components   = [c.strip() for c in cols[1].split(",") if c.strip()]
            mixtures[alias_lower] = components
            for word in alias_lower.split():
                if len(word) > 3:
                    mixtures.setdefault(word, components)

            # Parse optional mole-fraction column (col index 2)
            if len(cols) >= 3:
                frac_raw = cols[2]
                try:
                    fracs = [float(f.strip()) for f in frac_raw.split(",") if f.strip()]
                    if len(fracs) == len(components):
                        mixture_fracs[alias_lower] = dict(zip(components, fracs))
                except ValueError:
                    pass  # Non-numeric cell (e.g. header row)

        # ── Unsupported ───────────────────────────────────────────────────────
        elif section == "unsupported" and len(cols) >= 4:
            # 4-column format: Compound/Class | Colloquial Names | Category | Reason
            formal_names      = cols[0]
            colloquial_names  = cols[1]
            reason            = cols[3]
            # Register all formal names (comma-separated within the cell)
            for name in formal_names.split(","):
                name = name.strip()
                if name:
                    unsupported[name.lower()] = reason
            # Register all colloquial names
            for name in colloquial_names.split(","):
                name = name.strip()
                if name and len(name) >= 3:
                    unsupported[name.lower()] = reason

    return lookup, mixtures, mixture_fracs, unsupported, unverified


# Exported for the test suite only — agent instances re-parse on __init__
_LOOKUP, _MIXTURES, _MIXTURE_FRACS, _UNSUPPORTED, _UNVERIFIED = (
    _parse_database(COMPOUND_DATABASE))


# ── Result type ────────────────────────────────────────────────────────────────

@dataclass
class BasisResult:
    compound_map:           dict[str, str | list[str]]   # original text → dwsim name(s)
    dwsim_compounds:        list[str]                    # flat unique DWSIM list
    normalised_description: str
    # Key = original user text (e.g. "natural gas"), value = {dwsim_name: mole_fraction}.
    # Downstream agents should iterate dwsim_compounds for the compound list and use
    # this dict only to initialise feed compositions.
    suggested_compositions: dict[str, dict[str, float]] = field(default_factory=dict)
    concentration_hints:    list[str]                   = field(default_factory=list)
    warnings:               list[str]                   = field(default_factory=list)
    errors:                 list[str]                   = field(default_factory=list)
    stage:                  str  = "LOOKUP"             # LOOKUP | LLM | PARTIAL
    stage1_count:           int  = 0
    success:                bool = True

    def summary(self) -> str:
        lines = [
            f"Stage: {self.stage}   Success: {self.success}   "
            f"Stage1 anchors: {self.stage1_count}",
            f"DWSIM compounds: {self.dwsim_compounds}",
        ]
        for orig, dwsim in self.compound_map.items():
            lines.append(f"  {orig!r:30s} → {dwsim}")
        if self.suggested_compositions:
            lines.append("Suggested compositions:")
            for alias, comp in self.suggested_compositions.items():
                lines.append(f"  {alias}: {comp}")
        if self.concentration_hints:
            lines.append("Concentration hints:")
            lines.extend(f"  {h}" for h in self.concentration_hints)
        if self.warnings:
            lines.append("Warnings:")
            lines.extend(f"  ⚠ {w}" for w in self.warnings)
        if self.errors:
            lines.append("Errors:")
            lines.extend(f"  ✗ {e}" for e in self.errors)
        return "\n".join(lines)


# ── LLM prompt ────────────────────────────────────────────────────────────────

# string.Template is used so that bare { } in the database markdown
# (e.g. code examples in the How-to-Update section) do not cause KeyError.
_SYSTEM_TEMPLATE = Template("""\
You are a chemical engineering expert and DWSIM compound identifier acting as a VERIFIER-COMPLETER.

Your three tasks, in order:

1. VERIFY the Stage 1 anchor compounds listed below.
   Stage 1 used a word-boundary regex scan and may have false positives (e.g. "He"
   matched Helium when the user wrote a pronoun, "an" matched Acrylonitrile in
   "an ethanol feed"). Reject any anchor that is not a genuine compound in the
   process description.

2. COMPLETE by finding compounds Stage 1 missed -- IUPAC systematic names, trade
   names, novel abbreviations, compounds embedded in complex descriptions.

3. EXTRACT from the description text:
   - Mixture compositions or concentration values (e.g. "30 wt% NaOH", "50/50 molar").
   - Any multi-component alias that should be expanded (e.g. "natural gas").

Output ONLY valid JSON -- no markdown fences, no prose:
{
  "confirmed": ["<DWSIM name>", ...],
  "rejected": [
    {"proposed": "<DWSIM name>", "original_text": "<text in description>",
      "reason": "<why this is a false positive>"}
  ],
  "additional": [
    {"original_text": "<as written by user>", "dwsim_name": "<DWSIM name or null>",
      "is_mixture": false, "mixture_components": [],
      "mole_fractions": [],
      "status": "ok|unverified|unsupported", "note": null}
  ],
  "mixture_expansions": [
    {"original_text": "<alias>", "components": ["<DWSIM name>", ...],
      "mole_fractions": [0.xx, ...], "note": null}
  ],
  "concentration_hints": ["<e.g. feed is 30 wt% ethanol in water>"],
  "normalised_description": "<description with ALL compound mentions replaced by DWSIM names>"
}

Rules:
- CRITICAL: Use the exact compound name as written in the process description. Do not
  substitute chemical synonyms, isomers, or alternative names. If the description says
  "p-xylene", output "p-Xylene" — not "m-Xylene", not "Xylene". The description text
  is authoritative for compound identity. This applies to all positional isomers
  (o-/m-/p-), chain isomers (n-/iso-/sec-/tert-), and stereoisomers.
- MUST use compound names verbatim from the database below — exact spelling and capitalisation required.
- MUST NOT invent, paraphrase, abbreviate, or translate compound names not in the database.
- If a compound is in the Unsupported section, set status = "unsupported".
- If a compound is not in the database, set status = "unverified" and make your
  best guess at the DWSIM name.
- mole_fractions must sum to 1.0 for each mixture expansion.
- "confirmed" lists DWSIM names (not original text).

---
$database
""")


# ── Few-shot example for Stage 2 LLM ─────────────────────────────────────────

_FEW_SHOT_BASIS = """\
━━━ EXAMPLE — VERIFY + COMPLETE + EXTRACT ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Stage 1 anchors: {"He": "Helium", "ethanol": "Ethanol"}
Process description: He mixed 70/30 ethanol and water then flashed the blend.

Expected output:
{
  "confirmed": ["Ethanol"],
  "rejected": [
    {"proposed": "Helium", "original_text": "He",
     "reason": "He is a pronoun — Helium is not present in this process"}
  ],
  "additional": [
    {"original_text": "water", "dwsim_name": "Water",
     "is_mixture": false, "mixture_components": [], "mole_fractions": [],
     "status": "ok", "note": null}
  ],
  "mixture_expansions": [],
  "concentration_hints": ["Feed is 70/30 ethanol/water molar split"],
  "normalised_description": "He mixed 70/30 Ethanol and Water then flashed the blend."
}

━━━ NOW PROCESS THE ACTUAL DESCRIPTION ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
"""


# ── Basis Agent ────────────────────────────────────────────────────────────────

class BasisAgent:
    """
    Normalises compound names to exact DWSIM names before the Planner runs.

    Stage 1 scans the description for known aliases (deterministic, zero cost).
    Stage 2 passes Stage 1 anchors + description to an LLM that acts as a
    verifier-completer: it rejects false positives, finds missed compounds,
    and extracts composition hints.

    Args:
        model: any model string recognised by agents/llm.py
    """

    def __init__(self, model: str = DEFAULT_MODEL):
        self._model = model
        self._lookup, self._mixtures, self._mixture_fracs, self._unsupported, \
            self._unverified = _parse_database(COMPOUND_DATABASE)
        self._system = _SYSTEM_TEMPLATE.substitute(database=COMPOUND_DATABASE)

    def identify(self, description: str,
                 feedback: list[str] | None = None) -> BasisResult:
        """
        Extract and normalise all compound names in a process description.

        Runs Stage 1 (deterministic scan) always. Stage 2 (LLM verifier-
        completer) is skipped when Stage 1 found at least one compound and all
        anchors are verified non-mixture aliases — it adds nothing in that case.
        If the LLM call fails the agent returns Stage 1 results with a warning.
        """
        # ── Unsupported check ────────────────────────────────────────────────
        # Must happen before Stage 1 so electrolytes / polymers are caught even
        # when their colloquial name (brine, caustic, lye …) is not in _LOOKUP.
        errors = self._check_unsupported(description)
        if errors:
            return BasisResult(
                compound_map={},
                dwsim_compounds=[],
                normalised_description=description,
                errors=errors,
                stage="LOOKUP",
                success=False,
            )

        # ── Stage 1 — deterministic anchor scan ──────────────────────────────
        anchors = self._stage1_scan(description)
        stage1_count = len(anchors)

        # ── Pure-component short-circuit ──────────────────────────────────────
        # When the description explicitly uses "pure" (e.g. "pure methane feed",
        # "pure component") AND Stage 1 resolved it to exactly one compound,
        # Stage 2 must not run — it tends to hallucinate companions like n-Butane
        # for what is genuinely a single-compound system.
        if (not feedback
                and re.search(r'\bpure\b', description, re.IGNORECASE)
                and anchors
                and all(isinstance(v, str) for v in anchors.values())
                and len(set(anchors.values())) == 1):
            return self._build_from_anchors(
                description, anchors, stage1_count,
                extra_warnings=["[basis] pure-component: Stage 2 skipped"],
                stage="LOOKUP",
            )

        # ── Stage 2 skip — all anchors verified, no LLM needed ───────────────
        if not feedback and self._can_skip_stage2(anchors, description):
            return self._build_from_anchors(
                description, anchors, stage1_count,
                extra_warnings=[], stage="LOOKUP",
            )

        # ── Stage 2 — LLM verifier-completer ─────────────────────────────────
        return self._stage2_llm(description, anchors, stage1_count, feedback=feedback)

    # ── Stage 2 skip guard ────────────────────────────────────────────────────

    def _can_skip_stage2(
            self,
            anchors: dict[str, str | list[str]],
            description: str,
    ) -> bool:
        if not anchors:
            return False  # Stage 1 found nothing — LLM needed to find missed compounds
        if any(isinstance(v, list) for v in anchors.values()):
            return False  # Mixture alias present — LLM needed to extract compositions
        if any(v in self._unverified for v in anchors.values() if isinstance(v, str)):
            return False  # Unverified compound — LLM can double-check
        # All anchors are verified single compounds — Stage 2 adds nothing
        return True

    # ── Stage 1 ───────────────────────────────────────────────────────────────

    def _stage1_scan(
            self, description: str,
    ) -> dict[str, str | list[str]]:
        """
        Scan description for known aliases using word-boundary regex.
        Longer aliases are checked first to avoid partial-phrase shadowing.

        Returns {original_text_in_description → dwsim_name_or_list}.
        These are *anchors* (candidates), not final results — Stage 2 verifies them.
        """
        anchors: dict[str, str | list[str]] = {}

        # Mixtures first (longer, more specific phrases take priority)
        for alias in sorted(self._mixtures, key=len, reverse=True):
            m = _word_match(alias, description)
            if m:
                original = m.group(0)
                anchors[original] = self._mixtures[alias]

        # Single-compound aliases
        for alias in sorted(self._lookup, key=len, reverse=True):
            m = _word_match(alias, description)
            if m:
                original = m.group(0)
                if original not in anchors:
                    anchors[original] = self._lookup[alias]

        return anchors

    # ── Stage 2 ───────────────────────────────────────────────────────────────

    def _stage2_llm(
            self,
            description: str,
            anchors: dict[str, str | list[str]],
            stage1_count: int,
            feedback: list[str] | None = None,
    ) -> BasisResult:
        """
        LLM verifier-completer: confirm/reject anchors, find missed compounds,
        extract composition and concentration information.

        Falls back to Stage 1 anchors (with a warning) on LLM failure.
        """
        anchor_summary = (
            json.dumps(
                {orig: (dwsim if isinstance(dwsim, str) else dwsim)
                 for orig, dwsim in anchors.items()},
                indent=2,
            ) if anchors else "  (none)"
        )
        prompt = (
            _FEW_SHOT_BASIS
            + f"Stage 1 anchors (verify these):\n{anchor_summary}\n\n"
            + f"Process description:\n{description}\n\n"
            + "Perform VERIFY → COMPLETE → EXTRACT and return JSON."
        )
        if feedback:
            feedback_block = "\n".join(f"  - {f}" for f in feedback)
            prompt += (
                f"\n\nDWSIM execution feedback (these errors occurred — fix the "
                f"compound names that caused them):\n{feedback_block}"
            )

        last_exc: Exception | None = None
        parsed = None
        for attempt in range(2):
            try:
                raw    = chat(prompt, system=self._system, model=self._model,
                              temperature=retry_temperature(attempt), thinking=False)
                parsed = _parse_llm_response(raw)
                break
            except Exception as exc:
                last_exc = exc

        if parsed is None:
            # Graceful degradation — never silently drop Stage 1 results
            warnings = [
                f"LLM verifier-completer failed ({last_exc}). "
                "Using Stage 1 anchors only — manual review recommended."
            ]
            return self._build_from_anchors(
                description, anchors, stage1_count,
                extra_warnings=warnings, stage="PARTIAL",
            )

        return self._merge_llm_output(
            description, anchors, stage1_count, parsed)

    def _merge_llm_output(
            self,
            description: str,
            anchors: dict[str, str | list[str]],
            stage1_count: int,
            parsed: dict,
    ) -> BasisResult:
        """Merge LLM verifier-completer output with Stage 1 anchors."""
        compound_map:        dict[str, str | list[str]]  = {}
        suggested_comps:     dict[str, dict[str, float]] = {}
        concentration_hints: list[str]                   = []
        warnings:            list[str]                   = []
        errors:              list[str]                   = []

        confirmed_dwsim  = set(parsed.get("confirmed", []))
        rejected_dwsim   = {r["proposed"] for r in parsed.get("rejected", [])}

        # ── Apply Stage 1 anchors, filtered by LLM verification ──────────────
        for orig, dwsim in anchors.items():
            dwsim_key = dwsim if isinstance(dwsim, str) else ", ".join(dwsim)
            if isinstance(dwsim, str) and dwsim in rejected_dwsim:
                warnings.append(
                    f"Stage 1 anchor '{orig}' → '{dwsim}' rejected by LLM verifier: "
                    + next(
                        (r.get("reason", "false positive")
                         for r in parsed.get("rejected", [])
                         if r["proposed"] == dwsim),
                        "false positive",
                    )
                )
                continue
            compound_map[orig] = dwsim
            if isinstance(dwsim, list):
                warnings.append(
                    f"'{orig}' is a mixture alias → {dwsim}. "
                    "Specify molar compositions in your description."
                )
                # Attach known mole fractions if available
                fracs = self._mixture_fracs.get(orig.lower())
                if fracs:
                    suggested_comps[orig] = fracs
            elif dwsim in self._unverified:
                warnings.append(
                    f"'{dwsim}' (from '{orig}') is marked unverified in "
                    "compound_database.md — confirm DWSIM accepts this name."
                )

        # ── Additional compounds found by LLM ─────────────────────────────────
        for c in parsed.get("additional", []):
            original = c.get("original_text", "")
            status   = c.get("status", "ok")
            note     = c.get("note")

            if c.get("is_mixture") or c.get("mixture_components"):
                comps  = c.get("mixture_components", [])
                fracs  = c.get("mole_fractions", [])
                compound_map[original] = comps
                warnings.append(
                    f"'{original}' expanded to {comps}. "
                    "Specify molar compositions in your description."
                )
                if fracs and len(fracs) == len(comps):
                    suggested_comps[original] = dict(zip(comps, fracs))
            elif status == "unsupported":
                errors.append(
                    f"'{original}' is unsupported: "
                    f"{note or 'see compound_database.md unsupported section'}"
                )
            else:
                dwsim = c.get("dwsim_name", "")
                if not dwsim:
                    continue
                if original not in compound_map:
                    compound_map[original] = dwsim
                # Validate against the full DWSIM compound list (1488 names).
                fuzzy = _fuzzy_match_dwsim(dwsim)
                if fuzzy:
                    canonical, match_type = fuzzy
                    if match_type == "fuzzy":
                        warnings.append(
                            f"'{dwsim}' (from '{original}') corrected to "
                            f"'{canonical}' via DWSIM compound list."
                        )
                    compound_map[original] = canonical
                    if status == "unverified":
                        warnings.append(
                            f"'{canonical}' (from '{original}') matched the "
                            "DWSIM list but was flagged unverified by the LLM "
                            "— confirm it is the right compound."
                        )
                else:
                    # Not in full list — genuinely unknown or hallucinated name.
                    # Offer a 'did you mean?' hint when the list is populated.
                    suggestion = _closest_dwsim_suggestion(dwsim)
                    did_you_mean = (
                        f" Did you mean '{suggestion}'?" if suggestion else ""
                    )
                    if status == "unverified" or dwsim in self._unverified:
                        warnings.append(
                            f"'{dwsim}' (from '{original}') not found in the DWSIM "
                            f"compound list.{did_you_mean} Confirm the exact DWSIM name "
                            "or add it to compound_database.md."
                        )
                    else:
                        warnings.append(
                            f"'{dwsim}' (from '{original}') not found in the DWSIM "
                            f"compound list.{did_you_mean} "
                            "Add the correct DWSIM name to compound_database.md and "
                            "rag/sources/compound_synonyms.json."
                        )
                if note and status == "ok":
                    warnings.append(f"'{original}': {note}")

        # ── Mixture expansions ────────────────────────────────────────────────
        for mx in parsed.get("mixture_expansions", []):
            orig   = mx.get("original_text", "")
            comps  = mx.get("components", [])
            fracs  = mx.get("mole_fractions", [])
            note   = mx.get("note")
            if orig and comps:
                compound_map[orig] = comps
                if fracs and len(fracs) == len(comps):
                    suggested_comps[orig] = dict(zip(comps, fracs))
                msg = f"'{orig}' expanded to {comps}."
                if note:
                    msg += f" Note: {note}"
                warnings.append(msg)

        # ── Concentration hints ───────────────────────────────────────────────
        for hint in parsed.get("concentration_hints", []):
            if hint:
                concentration_hints.append(hint)

        normalised = parsed.get("normalised_description") or _substitute(
            description, compound_map)

        _dwsim, _canon_warns = canonicalize_list(_flatten(compound_map))
        warnings += _canon_warns
        return BasisResult(
            compound_map=compound_map,
            dwsim_compounds=_dwsim,
            normalised_description=normalised,
            suggested_compositions=suggested_comps,
            concentration_hints=concentration_hints,
            warnings=warnings,
            errors=errors,
            stage="LLM",
            stage1_count=stage1_count,
            success=len(errors) == 0,
        )

    # ── Fallback builder ──────────────────────────────────────────────────────

    def _build_from_anchors(
            self,
            description: str,
            anchors: dict[str, str | list[str]],
            stage1_count: int,
            extra_warnings: list[str],
            stage: str,
    ) -> BasisResult:
        """Build a BasisResult directly from Stage 1 anchors (LLM unavailable)."""
        warnings = list(extra_warnings)
        suggested_comps: dict[str, dict[str, float]] = {}
        for orig, dwsim in anchors.items():
            if isinstance(dwsim, list):
                warnings.append(
                    f"'{orig}' is a mixture alias → {dwsim}. "
                    "Specify molar compositions in your description."
                )
                fracs = self._mixture_fracs.get(orig.lower())
                if fracs:
                    suggested_comps[orig] = fracs
            elif dwsim in self._unverified:
                warnings.append(
                    f"'{dwsim}' (from '{orig}') is unverified in "
                    "compound_database.md — confirm DWSIM accepts this name."
                )
        _dwsim, _canon_warns = canonicalize_list(_flatten(anchors))
        warnings += _canon_warns
        return BasisResult(
            compound_map=anchors,
            dwsim_compounds=_dwsim,
            normalised_description=_substitute(description, anchors),
            suggested_compositions=suggested_comps,
            warnings=warnings,
            stage=stage,
            stage1_count=stage1_count,
            success=True,
        )

    # ── Unsupported check ─────────────────────────────────────────────────────

    def _check_unsupported(self, description: str) -> list[str]:
        """
        Scan for unsupported compound keywords using word-boundary matching.
        Checks both formal names and colloquial aliases (brine, caustic, lye…).
        Longer keywords are checked first to avoid phrase fragmentation.
        """
        errors: list[str] = []
        seen_reasons: set[str] = set()
        for keyword in sorted(self._unsupported, key=len, reverse=True):
            if _word_match(keyword, description):
                reason = self._unsupported[keyword]
                if reason not in seen_reasons:
                    errors.append(
                        f"'{keyword}' detected: {reason}. "
                        "Remove this compound or use a supported alternative."
                    )
                    seen_reasons.add(reason)
        return errors


# ── Helpers ───────────────────────────────────────────────────────────────────

def _word_match(alias: str, description: str):
    """
    Return the first regex Match if alias appears as a complete token in
    description, or None. Negative lookaround prevents substring hits
    (e.g. 'ethanol' must not fire inside 'diethanolamine').
    Case-insensitive.
    """
    pattern = r'(?<![A-Za-z0-9])' + re.escape(alias) + r'(?![A-Za-z0-9])'
    return re.search(pattern, description, re.IGNORECASE)


def _substitute(description: str, resolved: dict[str, str | list[str]]) -> str:
    """Replace original mentions with DWSIM names using word-boundary regex."""
    result = description
    for original, dwsim in sorted(resolved.items(), key=lambda x: len(x[0]), reverse=True):
        replacement = ", ".join(dwsim) if isinstance(dwsim, list) else dwsim
        pattern = re.compile(
            r'(?<![A-Za-z0-9])' + re.escape(original) + r'(?![A-Za-z0-9])',
            re.IGNORECASE,
        )
        result = pattern.sub(replacement, result)
    return result


def _flatten(compound_map: dict[str, str | list[str]]) -> list[str]:
    """Flat de-duplicated list of DWSIM compound names."""
    seen   = set()
    result = []
    for v in compound_map.values():
        names = v if isinstance(v, list) else [v]
        for name in names:
            if name not in seen:
                seen.add(name)
                result.append(name)
    return result


def _fuzzy_match_dwsim(name: str) -> tuple[str, str] | None:
    """
    Validate a proposed DWSIM compound name against the full compound list.

    Resolution order (first match wins):
      1. exact        — case-insensitive exact match in _DWSIM_ALL
      2. synonym      — match via _DWSIM_SYNONYMS (IUPAC/common/abbreviation aliases)
      3. edit_dist    — Levenshtein distance ≤ 2 against all DWSIM names
      4. difflib      — sequence similarity ≥ 85% (handles minor spelling variants)

    Returns (canonical_name, match_type) or None if no acceptable match found.
    """
    if not _DWSIM_ALL:
        return None
    lower = name.lower()

    # 1. Exact case-insensitive match
    exact = _DWSIM_ALL.get(lower)
    if exact:
        return exact, "exact"

    # 2. Synonym lookup
    syn = _DWSIM_SYNONYMS.get(lower)
    if syn:
        return syn, "synonym"

    # 3. Levenshtein edit distance ≤ 2 (skip keys where length diff alone exceeds budget)
    best_dist, best_key = 3, None
    for key in _DWSIM_ALL:
        if abs(len(lower) - len(key)) > 2:
            continue
        d = _levenshtein(lower, key)
        if d < best_dist:
            best_dist, best_key = d, key
    if best_key is not None and best_dist <= 2:
        return _DWSIM_ALL[best_key], "edit_dist"

    # 4. difflib sequence similarity ≥ 85%
    matches = difflib.get_close_matches(lower, _DWSIM_ALL.keys(), n=1, cutoff=0.85)
    if matches:
        return _DWSIM_ALL[matches[0]], "fuzzy"

    return None


def _closest_dwsim_suggestion(name: str) -> str | None:
    """
    Return the most similar DWSIM compound name for a 'did you mean?' hint,
    even when below the strict fuzzy-match threshold.
    Returns None when _DWSIM_ALL is empty or no reasonable match exists.
    """
    if not _DWSIM_ALL:
        return None
    matches = difflib.get_close_matches(name.lower(), _DWSIM_ALL.keys(), n=1, cutoff=0.5)
    return _DWSIM_ALL[matches[0]] if matches else None


def _parse_llm_response(raw: str) -> dict:
    text = raw.strip()
    if text.startswith("```"):
        lines = text.splitlines()
        text  = "\n".join(ln for ln in lines if not ln.strip().startswith("```"))
    text = text.strip()
    match = re.search(r'\{.*\}', text, re.DOTALL)
    if match:
        return json.loads(match.group(0))
    return json.loads(text)
